@startuml RavenDB

hide circle
skinparam linetype ortho

' ---- Entities ----
entity User {
    * id : text <<Keycloak ID>>
    --
    * username : text
    * org_affiliation : text <<FK>> (Organization.id)
    * user_type_id : text <<FK>> (UserType.id)
}

entity Organization {
    * id : text
    --
    * org_name : text
    * org_address : text
    * org_city : text
    * org_type : integer Enum: coe/academic/industry
}

entity UserType {
    * id : text
    --
    * name : text
    * description : text
    * metadata_search : integer  ' Enum: none/View/Edit/Delete/Create
    * data_access : integer      ' Enum: none/yes
    * cohort_builder : integer   ' Enum: none/yes
    * data_quality : integer     ' Enum: none/View/Export
    * algorithms : integer       ' Enum: none/View/Edit/Delete/Export/Create
    * results_report : integer   ' Enum: none/View/Edit/Export
}

entity Workspace {
    * id : text
    --
    * name : text
    * description : text
    * status : integer
    * creation_date : timestamp
    * creator_id : text <<FK>> (User.id)
    * last_modification_date : timestamp
    * metadata_search : integer  ' Enum: pending/in progress/completed
    * data_access : integer      ' Enum: pending/initiated/submitted/rejected/granted/expired
    * data_analysis : integer    ' Enum: pending/in progress/completed
    * result_report : integer    ' Enum: pending/in progress/completed
    * v6_study_id : text
}

entity Permit {
    * id : text
    --
    * permit_name : text
    * creation_date : timestamp
    * update_date : timestamp
    * expiring_date : timestamp
    * status : integer ' Enum: pending/initiated/submitted/rejected/granted/expired/cancelled
    * workspace_id : text <<FK>> (Workspace.id)
    * metadata_id : text <<FK>> (MetadataSearch.id)
}

entity MetadataSearch {
    * id : text
    --
    * update_date : timestamp
    * created_date : timestamp
    * creator_id : text <<FK>> (User.id)
    * type_cancer : text
    * workspace_id : text <<FK>> (Workspace.id)
    * status : integer
}

entity WorkspaceHistory {
    * id : text
    --
    * date : timestamp
    * action : text
    * phase : text
    * details : text
    * creator_id : text <<FK>> (User.id)
    * workspace_id : text <<FK>> (Workspace.id)
}

entity Analysis {
    * id : text
    --
    * analysis_name : text
    * analysis_description : text
    * creation_date : timestamp
    * update_date : timestamp
    * expiring_date : timestamp
    * user_id : text <<FK>> (User.id)
    * workspace_id : text <<FK>> (Workspace.id)
}

entity Cohort {
    * id : text
    --
    * cohort_name : text
    * cohort_description : text
    * creation_date : timestamp
    * update_date : timestamp
    * status : integer
    * cohort_query : text
    * user_id : text <<FK>> (User.id)
    * analysis_id : text <<FK>> (Analysis.id)
    * workspace_id : text <<FK>> (Workspace.id)
}

entity CohortResult {
    * cohort_id : text <<FK>> (Cohort.id)
    * data_id : text
}

entity Algorithm {
    * id : text
    --
    * method_name : text
    * creation_date : timestamp
    * update_date : timestamp
    * input : json
    * execution_status : integer
    * analysis_id : text <<FK>> (Analysis.id)
    * workspace_id : text <<FK>> (Workspace.id)
}

entity CohortAlgorithm {
    * cohort_id : text <<FK>> (Cohort.id)
    * algorithm_id : text <<FK>> (Algorithm.id)
}

' ---- Relationships ----
User ||--|| UserType
User ||--|| Organization
Workspace ||--o{ Analysis
Workspace ||--o{ WorkspaceHistory
Workspace ||--o{ Permit
Workspace ||--o{ MetadataSearch
Analysis ||--o{ Cohort
Analysis ||--o{ Algorithm
Cohort ||--o{ CohortResult
Cohort ||--o{ CohortAlgorithm
Algorithm ||--o{ CohortAlgorithm

@enduml
