@startuml RavenDB
' configuration
hide circle
skinparam linetype ortho
'

entity User  {
    * Id : string
    --
    * Name : string
    * Email : string
    * Password : string
    * Role : string
}

@enduml